import clsx from 'clsx'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ClNavbar from '../components/ClNavbar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'flex flex-col')}>
        <ClNavbar />
        <div className="flex-1">
          {children}
        </div>
      </body>
    </html>
  )
}
